#!/usr/bin/env bash
MODULE_NAME="thunar"
MODULE_DESCRIPTION="Thunar graphical file manager"
MODULE_VERSION="1.0.0"
MODULE_DEPENDENCIES=("core")
MODULE_ARCHITECTURES=("x86_64" "aarch64")
MODULE_ENABLED_BY_DEFAULT=true
