[config]
mode = "dark"
variant = "scheme-tonal-spot"

[templates.hyprland-colors]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.waybar-colors]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"

[templates.rofi-colors]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/colors.rasi"

[templates.swaync-colors]
input_path = "~/.config/matugen/templates/swaync-colors.css"
output_path = "~/.config/swaync/colors.css"

[templates.hyprlock-colors]
input_path = "~/.config/matugen/templates/hyprlock-colors.conf"
output_path = "~/.config/hyprlock/colors.conf"

[templates.ghostty-colors]
input_path = "~/.config/matugen/templates/ghostty-colors"
output_path = "~/.config/ghostty/colors"

[templates.fish-colors]
input_path = "~/.config/matugen/templates/fish-colors.fish"
output_path = "~/.config/fish/conf.d/colors.fish"
