#!/usr/bin/env bash
MODULE_NAME="vscode"
MODULE_DESCRIPTION="Visual Studio Code editor"
MODULE_VERSION="1.0.0"
MODULE_DEPENDENCIES=("core")
MODULE_ARCHITECTURES=("x86_64")
MODULE_ENABLED_BY_DEFAULT=true
