# Generated by matugen — do not edit manually.
# Source: ~/.config/matugen/templates/fish-colors.fish
# Re-generate: matugen image ~/Pictures/Wallpapers/current.jpg
# Sourced automatically from conf.d/ on fish startup.

set -gx fish_color_command        "{{colors.primary.default.hex}}"
set -gx fish_color_keyword        "{{colors.secondary.default.hex}}"
set -gx fish_color_param          "{{colors.on_background.default.hex}}"
set -gx fish_color_quote          "{{colors.tertiary.default.hex}}"
set -gx fish_color_redirection    "{{colors.on_surface_variant.default.hex}}"
set -gx fish_color_end            "{{colors.on_surface_variant.default.hex}}"
set -gx fish_color_error          "{{colors.error.default.hex}}"
set -gx fish_color_comment        "{{colors.outline.default.hex}}"
set -gx fish_color_selection      --background="{{colors.surface_container.default.hex}}"
set -gx fish_color_search_match   --background="{{colors.surface_container_high.default.hex}}"
set -gx fish_color_operator       "{{colors.secondary.default.hex}}"
set -gx fish_color_escape         "{{colors.primary.default.hex}}"
set -gx fish_color_autosuggestion "{{colors.outline_variant.default.hex}}"
set -gx fish_color_cancel         "{{colors.error.default.hex}}"
